source/Otzovik/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/accounts/urls.py
from django.urls import path

from accounts.views import UserDetailView, RegisterView, UserChangeView, UserPasswordChangeView
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/', RegisterView.as_view(), name='create'),
    path('<int:pk>/', UserDetailView.as_view(), name='detail'),
    path('change/',  UserChangeView.as_view(), name='change'),
    path('password_change/', UserPasswordChangeView.as_view(), name='password_change'),
]

source/webapp/urls.py
from django.contrib import admin
from django.urls import path
from webapp.views import ProductList, ProductDetail, ProductCreate, ProductDelete, ProductUpdate, ReviewCreate, \
    ReviewDeleteView, ReviewUpdateView
from django.views.generic import RedirectView

app_name = 'webapp'


urlpatterns = [
    path('', RedirectView.as_view(pattern_name='webapp:index')),
    path('index/', ProductList.as_view(), name='index'),
    path('product/<int:pk>/view/', ProductDetail.as_view(), name='product_view'),
    path('product/<int:pk>/update/', ProductUpdate.as_view(), name='product_update'),
    path('product/<int:pk>/delete/', ProductDelete.as_view(), name='product_delete'),
    path('product/add/', ProductCreate.as_view(), name='product_add'),
    path('product/<int:pk>/review/add/', ReviewCreate.as_view(), name='product_review_add'),
    path('review/<int:pk>/update', ReviewUpdateView.as_view(), name='review_update'),
    path('review/<int:pk>/delete', ReviewDeleteView.as_view(), name='review_delete'),
    path('redirect_view/', RedirectView.as_view())
]

source/webapp/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse
CATEGORY_CHOICES = [('Clothes', 'Одежда'), ('Tools', 'Инструменты'), ('Equipments', 'Экиперовка')]


# Create your models here.
class Product(models.Model):
    title = models.CharField(max_length=60, verbose_name='Название')
    category = models.CharField(max_length=20, choices=CATEGORY_CHOICES, default=CATEGORY_CHOICES[0][0],
                              verbose_name="Категория")
    description = models.TextField(max_length=3000, null=True, blank=True, verbose_name='Описание')
    picture = models.ImageField(upload_to='images', null=True, blank=True, verbose_name='Картинка')

    def __str__(self):
        return f'{self.pk}. {self.title}. {self.category}. {self.picture}'

    def get_absolute_url(self):
        return reverse('webapp:product_view', kwargs={'pk': self.pk})

    def get_average(self):
        product = Product.objects.get(pk=self.pk)
        average = 0
        avg_list = []
        for review in product.product_reviews.all():
            if review.moderated:
                average += review.grade
                avg_list.append(review.grade)
        if average:
            return average / len(avg_list)
        return average

    class Meta:
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"


class Review(models.Model):
    user = models.ForeignKey(get_user_model(), related_name='reviews', blank=True, on_delete=models.CASCADE, verbose_name='Пользователь')
    product = models.ForeignKey('webapp.Product', on_delete=models.CASCADE, related_name='reviews', default=1,
                                verbose_name='Продукт')
    review_text = models.TextField(max_length=3000, blank=False, null=False, verbose_name='Отзыв')
    rating = models.IntegerField(null=False, blank=False, default=0, verbose_name='Оценка')
    moderated = models.BooleanField(null=False, blank=True, verbose_name="Модерирован")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Время изменения")

    class Meta:
        permissions = [
            ('can_add_moderated_to_the_review', 'Может модерировать отзыв'),
            ('can_view_moderated_to_the_review', 'Может видеть немодерированные отзывы'),
        ]
    # def __str__(self):
    #     return f'{self.pk}'

source/webapp/forms.py
from django import forms
from django.forms import widgets
from webapp.models import CATEGORY_CHOICES, Product, Review


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['review_text', 'user', 'rating', 'moderated']


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['title', 'description', 'category', 'picture']

source/webapp/views/base_views.py
from django.db.models import Q
from django.utils.http import urlencode
from django.views.generic import ListView


class SearchView(ListView):
    search_form_class = None
    search_form_field = 'search'
    query_name = 'query'
    search_fields = []


    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_search_form(self):
        if self.search_form_class:
            return self.search_form_class(self.request.GET)

    def get_search_value(self):
        if self.form:
            if self.form.is_valid():
                return self.form.cleaned_data[self.search_form_field]

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            queryset = queryset.filter(self.get_query()) # filter(Q()) == all()
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        if self.form:
            context['form'] = self.form
            if self.search_value:
                context[self.query_name] = urlencode({self.search_form_field: self.search_value})
                context[self.search_form_field] = self.search_value
        return context

    def get_query(self):
        query = Q()
        for field in self.search_fields:
            kwargs = {field: self.search_value}
            query = query | Q(**kwargs)
        return query

source/webapp/views/product_views.py
from webapp.forms import ProductForm
from webapp.models import Product
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse, reverse_lazy


class ProductList(ListView):
    model = Product
    template_name = 'product/index.html'
    context_object_name = 'products'
    paginate_by = 3
    ordering = ['category', 'title']


class ProductDetail(DetailView):
    model = Product
    template_name = 'product/product_view.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        product = self.object
        reviews = product.reviews.order_by('-created_at')
        context['reviews'] = reviews
        return context


class ProductCreate(CreateView):
    model = Product
    form_class = ProductForm
    template_name = 'product/create.html'

    def get_success_url(self):
        return reverse('webapp:product_view', kwargs={'pk': self.object.pk })


class ProductUpdate(UpdateView):
    model = Product
    form_class = ProductForm
    template_name = 'product/product_update.html'

    def get_success_url(self):
        return reverse('webapp:product_view', kwargs={'pk': self.object.pk })


class ProductDelete(DeleteView):
    model = Product
    template_name = "product/product_delete.html"
    success_url = reverse_lazy('webapp:index')

source/webapp/views/review_views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from django.views.generic import CreateView, UpdateView, DeleteView

from webapp.forms import ReviewForm
from webapp.models import Review, Product


class ReviewCreate(LoginRequiredMixin, CreateView):
    template_name = 'review/create.html'
    model = Review
    form_class = ReviewForm

    def get_success_url(self):
        return reverse('webapp:product_view', kwargs={'pk': self.object.product.pk})

    def form_valid(self, form):
        product = get_object_or_404(Product, pk=self.kwargs.get('pk'))
        form.instance.article = product
        form.instance.author = self.request.user
        return super().form_valid(form)


class ReviewUpdateView(PermissionRequiredMixin, UpdateView):
    model = Review
    template_name = 'review/update.html'
    form_class = ReviewForm
    context_object_name = 'review'

    def has_permission(self):
        return self.request.user.has_perm('webapp.change_review') or self.get_object().user == self.request.user

    def get_success_url(self):
        return reverse('webapp:product_view', kwargs={'pk': self.object.product.pk})


class ReviewDeleteView(UserPassesTestMixin, DeleteView):
    model = Review

    def test_func(self):
        return self.request.user.has_perm('webapp.delete_review') or self.get_object().user == self.request.user

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('webapp:product_view', kwargs={'pk': self.object.product.pk })

source/webapp/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <title>{% block title %}Store{% endblock %}</title>
</head>
<body>
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'webapp:index' %}">Список товаров</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                {% block nav %}{% endblock %}
                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                    <ul>

                    </ul>
                    </li>
                {% endif %}
            </div>
            {% if request.user.is_authenticated %}
                <p class="ms-auto text-secondary d-inline-block my-0 py-auto" >Привет, <a href="{% url 'accounts:detail' request.user.pk %}">{{ request.user.username }}</a></p>
                <a class="btn btn-dark ms-2"
                   href="{% url 'accounts:logout' %}?next={{ request.get_full_path }}">Выйти</a>
            {% else %}
                <a class="btn btn-dark ms-auto" href="{% url 'accounts:login' %}?next={% if request.GET.next %}{{ request.GET.next }}{% else %}{{ request.get_full_path }}{% endif %}">Войти</a>
                <a class="btn btn-outline-secondary ms-2" href="{% url 'accounts:create' %}?next={% if request.GET.next %}{{ request.GET.next }}{% else %}{{ request.get_full_path }}{% endif %}">Регистрация</a>
            {% endif %}
        </div>
    </div>
</nav>

<div class="container my-2">
    {% block content %}
    {% endblock %}
</div>

<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
        crossorigin="anonymous"></script>
</body>
</html>