source/Otzovik/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.contrib import admin
from django.urls import path
from webapp.views import ProductList, ProductDetail, ProductCreate, ProductDelete, ProductUpdate, ReviewCreate, \
    ReviewDeleteView, ReviewUpdateView
from django.views.generic import RedirectView

app_name = 'webapp'


urlpatterns = [
    path('', RedirectView.as_view(pattern_name='webapp:index')),
    path('index/', ProductList.as_view(), name='index'),
    path('product/<int:pk>/view/', ProductDetail.as_view(), name='product_view'),
    path('product/<int:pk>/update/', ProductUpdate.as_view(), name='product_update'),
    path('product/<int:pk>/delete/', ProductDelete.as_view(), name='product_delete'),
    path('product/add/', ProductCreate.as_view(), name='product_add'),
    path('product/<int:pk>/review/add/', ReviewCreate.as_view(), name='product_review_add'),
    path('review/<int:pk>/update', ReviewUpdateView.as_view(), name='review_update'),
    path('review/<int:pk>/delete', ReviewDeleteView.as_view(), name='review_delete'),
    path('redirect_view/', RedirectView.as_view())
]

source/webapp/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse
CATEGORY_CHOICES = [('Clothes', 'Одежда'), ('Tools', 'Инструменты'), ('Equipments', 'Экиперовка')]


# Create your models here.
class Product(models.Model):
    title = models.CharField(max_length=60, verbose_name='Название')
    category = models.CharField(max_length=20, choices=CATEGORY_CHOICES, default=CATEGORY_CHOICES[0][0],
                              verbose_name="Категория")
    description = models.TextField(max_length=3000, null=True, blank=True, verbose_name='Описание')
    picture = models.ImageField(upload_to='images', null=True, blank=True, verbose_name='Картинка')

    def __str__(self):
        return f'{self.pk}. {self.title}. {self.category}. {self.picture}'

    def get_absolute_url(self):
        return reverse('webapp:product_view', kwargs={'pk': self.pk})

    def get_average(self):
        product = Product.objects.get(pk=self.pk)
        average = 0
        avg_list = []
        for review in product.product_reviews.all():
            if review.moderated:
                average += review.grade
                avg_list.append(review.grade)
        if average:
            return average / len(avg_list)
        return average

    class Meta:
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"


class Review(models.Model):
    user = models.ForeignKey(get_user_model(), related_name='reviews', blank=True, on_delete=models.CASCADE, verbose_name='Пользователь')
    product = models.ForeignKey('webapp.Product', on_delete=models.CASCADE, related_name='reviews', default=1,
                                verbose_name='Продукт')
    review_text = models.TextField(max_length=3000, blank=False, null=False, verbose_name='Отзыв')
    rating = models.IntegerField(null=False, blank=False, default=0, verbose_name='Оценка')
    moderated = models.BooleanField(null=False, blank=True, verbose_name="Модерирован")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Время изменения")

    class Meta:
        permissions = [
            ('can_add_moderated_to_the_review', 'Может модерировать отзыв'),
            ('can_view_moderated_to_the_review', 'Может видеть немодерированные отзывы'),
        ]
    # def __str__(self):
    #     return f'{self.pk}'

source/webapp/forms.py
from django import forms
from django.forms import widgets
from webapp.models import CATEGORY_CHOICES, Product, Review


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['review_text', 'user', 'rating', 'moderated']


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['title', 'description', 'category', 'picture']

source/webapp/views/base_views.py
from django.db.models import Q
from django.utils.http import urlencode
from django.views.generic import ListView


class SearchView(ListView):
    search_form_class = None
    search_form_field = 'search'
    query_name = 'query'
    search_fields = []


    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_search_form(self):
        if self.search_form_class:
            return self.search_form_class(self.request.GET)

    def get_search_value(self):
        if self.form:
            if self.form.is_valid():
                return self.form.cleaned_data[self.search_form_field]

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            queryset = queryset.filter(self.get_query()) # filter(Q()) == all()
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        if self.form:
            context['form'] = self.form
            if self.search_value:
                context[self.query_name] = urlencode({self.search_form_field: self.search_value})
                context[self.search_form_field] = self.search_value
        return context

    def get_query(self):
        query = Q()
        for field in self.search_fields:
            kwargs = {field: self.search_value}
            query = query | Q(**kwargs)
        return query

source/webapp/views/product_views.py
from webapp.forms import ProductForm
from webapp.models import Product
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse, reverse_lazy


class ProductList(ListView):
    model = Product
    template_name = 'product/index.html'
    context_object_name = 'products'
    paginate_by = 3
    ordering = ['category', 'title']


class ProductDetail(DetailView):
    model = Product
    template_name = 'product/product_view.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        product = self.object
        reviews = product.reviews.order_by('-created_at')
        context['reviews'] = reviews
        return context


class ProductCreate(CreateView):
    model = Product
    form_class = ProductForm
    template_name = 'product/create.html'

    def get_success_url(self):
        return reverse('webapp:product_view', kwargs={'pk': self.object.pk })


class ProductUpdate(UpdateView):
    model = Product
    form_class = ProductForm
    template_name = 'product/product_update.html'

    def get_success_url(self):
        return reverse('webapp:product_view', kwargs={'pk': self.object.pk })


class ProductDelete(DeleteView):
    model = Product
    template_name = "product/product_delete.html"
    success_url = reverse_lazy('webapp:index')

source/webapp/views/review_views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from django.views.generic import CreateView, UpdateView, DeleteView

from webapp.forms import ReviewForm
from webapp.models import Review, Product


class ReviewCreate(LoginRequiredMixin, CreateView):
    template_name = 'review/create.html'
    model = Review
    form_class = ReviewForm

    def get_success_url(self):
        return reverse('webapp:product_view', kwargs={'pk': self.object.product.pk})

    def form_valid(self, form):
        product = get_object_or_404(Product, pk=self.kwargs.get('pk'))
        form.instance.article = product
        form.instance.author = self.request.user
        return super().form_valid(form)


class ReviewUpdateView(PermissionRequiredMixin, UpdateView):
    model = Review
    template_name = 'review/update.html'
    form_class = ReviewForm
    context_object_name = 'review'

    def has_permission(self):
        return self.request.user.has_perm('webapp.change_review') or self.get_object().user == self.request.user

    def get_success_url(self):
        return reverse('webapp:product_view', kwargs={'pk': self.object.product.pk})


class ReviewDeleteView(UserPassesTestMixin, DeleteView):
    model = Review

    def test_func(self):
        return self.request.user.has_perm('webapp.delete_review') or self.get_object().user == self.request.user

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('webapp:product_view', kwargs={'pk': self.object.product.pk })

source/webapp/templates/product/create.html
{% extends 'base.html' %}

{% block content %}

    <div class="card">
        <div class="card-body">
            <form action="" method="POST">
                {% include 'partial/product_form.html' with button_text='Создать' %}
            </form>
        </div>
    </div>

{% endblock %}

source/webapp/templates/product/index.html
{% extends 'base.html' %}

{% block nav %}
    {% if request.user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'webapp:product_add' %}">Add product</a>
        </li>
    {% endif %}
{% endblock %}

{% block content %}
    <h1>Список товаров</h1>
    {% include "partial/product_list.html" %}
{% endblock %}

source/webapp/templates/product/product_delete.html
{% extends 'base.html' %}

{% block content %}
    <h2>Вы действительно хотите удалить {{ product.title }}?</h2>
    <form action="" method="POST">
    {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Да">
        <a href="{% url 'webapp:product_view' product.pk %}" class="btn btn-success">Нет</a>
    </form>
{% endblock %}

source/webapp/templates/product/product_update.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="POST">
    {% include 'partial/product_form.html' with button_text='Изменить' %}
    </form>
{% endblock %}

source/webapp/templates/product/product_view.html
{% extends 'base.html' %}
{% load static %}
{% block nav %}

    {% if request.user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'webapp:product_add' %}">Add product</a>
        </li>

        {% if perms.webapp.change_product or article.user == request.user %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'webapp:product_update' product.pk %}">Update</a>
            </li>
        {% endif %}
        {% if perms.webapp.delete_product  or product.user == request.user %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'webapp:product_delete' product.pk %}">Delete</a>
            </li>
        {% endif %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'webapp:product_review_add' product.pk %}">Add review</a>
        </li>
    {% endif %}
{% endblock %}
{% block content %}
    <div class="card">
        <h5 class="card-header">{{ product.title }}</h5>
        <div class="card-body">
            <p class="card-text">Категория: {{ product.category }}</p>
            <p class="card-text">Описание товара: {{ product.description }}</p>
            <p>
            {% if product.picture %}
                <img src="{{ product.picture.url }}" class="card-img-top" style="width: 150px" alt="...">
            {% else %}
                <img src="{% static 'car.jpg' %}" class="card-img-top" style="width: 150px" alt="...">
            {% endif %}
            <br>
            </p>
            <a href="{% url 'webapp:product_update' product.pk %}" class="btn btn-primary">Редактировать</a>
            <a href="{% url 'webapp:product_delete' product.pk %}" class="btn btn-danger">Удалить</a>
        </div>
    </div>
{#    <p><b>Средняя оценка: {{ product.get_average }}</b></p>#}
            <h3 class="ms-3">Reviews:</h3>
    <div class="row">
        {% for review in reviews %}
            <div class="col-sm-4">
                <div class="card text-bg-light mb-3">
                    <div class="card-body">
                        <p class="card-text">Review: {{ review.review_text }}</p>
                        <p class="card-text">Rating: {{ review.rating }}</p>
                        <p class="card-text">User name: {{ review.user }}</p>
                        <p class="card-text">Mail: {{ review.get.user.email }}</p>
                        <div class="d-flex justify-content-around">
                            {% if perms.webapp.change_review or review.user == request.user %}
                                <a href="{% url 'webapp:review_update' review.pk %}"
                                   class="btn btn-success px-5">Update</a>
                            {% endif %}
                            {% if perms.webapp.delete_review or review.user == request.user %}
                                <a href="{% url 'webapp:review_delete' review.pk %}"
                                   class="btn btn-danger px-5">Delete</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        {% empty %}
            <p>Отзывов нет</p>
        {% endfor %}
    </div>
{% endblock %}